In [24]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score,classification_report

In [3]:
df = pd.read_csv(r"C:\Users\tanma\Downloads\DATASETS\penguins_size_dataset\penguins_size.csv")

In [4]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [6]:
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [8]:
num_cols = ['culmen_length_mm', 'culmen_depth_mm', 
            'flipper_length_mm', 'body_mass_g']

imputer = SimpleImputer(strategy='median')
df[num_cols] = imputer.fit_transform(df[num_cols])

In [9]:
df['sex'].fillna(df['sex'].mode()[0], inplace=True)

C:\Users\tanma\AppData\Local\Temp\ipykernel_2604\1222584612.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['sex'].fillna(df['sex'].mode()[0], inplace=True)


In [10]:
df.isnull().sum()

species              0
island               0
culmen_length_mm     0
culmen_depth_mm      0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [11]:
# label encoding
le = LabelEncoder()

df['species'] = le.fit_transform(df['species'])
df['island'] = le.fit_transform(df['island'])
df['sex'] = le.fit_transform(df['sex'])

In [12]:
x = df.drop('species', axis=1)
y = df['species']

In [16]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=42
)

In [30]:
#feature scaling 
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
#logistic Regression model
from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression()
LR_model.fit(X_train, y_train)

LogisticRegression()

In [32]:
y_pred = LR_model.predict(X_test)

In [33]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("classification report :",classification_report(y_test, y_pred))

Accuracy: 0.9903846153846154
classification report :               precision    recall  f1-score   support

           0       0.98      1.00      0.99        50
           1       1.00      0.95      0.97        20
           2       1.00      1.00      1.00        34

    accuracy                           0.99       104
   macro avg       0.99      0.98      0.99       104
weighted avg       0.99      0.99      0.99       104



In [47]:
# Random forest classifier model 
from sklearn.ensemble import RandomForestClassifier

RF_model = RandomForestClassifier(n_estimators = 300)
RF_model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=300)

In [48]:
y_pred = RF_model.predict(X_test)

In [49]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("classification report :",classification_report(y_test, y_pred))

Accuracy: 0.9807692307692307
classification report :               precision    recall  f1-score   support

           0       0.98      0.98      0.98        50
           1       0.95      0.95      0.95        20
           2       1.00      1.00      1.00        34

    accuracy                           0.98       104
   macro avg       0.98      0.98      0.98       104
weighted avg       0.98      0.98      0.98       104



In [50]:
#confusion matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[49  1  0]
 [ 1 19  0]
 [ 0  0 34]]


In [54]:
#Decision tree classifier 

from sklearn.tree import DecisionTreeClassifier
DT_model = DecisionTreeClassifier(max_depth = 4,random_state=42)
DT_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

In [55]:
y_pred = DT_model.predict(X_test)

In [56]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("classification report :",classification_report(y_test, y_pred))

Accuracy: 0.9615384615384616
classification report :               precision    recall  f1-score   support

           0       0.98      0.96      0.97        50
           1       0.86      0.95      0.90        20
           2       1.00      0.97      0.99        34

    accuracy                           0.96       104
   macro avg       0.95      0.96      0.95       104
weighted avg       0.96      0.96      0.96       104

